[sciam-computing]
title = "SciAm Computing"
url = "https://www.scientificamerican.com/computing/"
entrySelector = "article"
titleSelector = "h2 p"
linkSelector = "a"
contentSelector = "section div p"
