[sciam-computing]
title = "SciAm Computing"
url = "https://www.scientificamerican.com/computing/"
entrySelector = "article"
titleSelector = "h2 p"
linkSelector = "a"
contentSelector = "section div p"

[arxiv-ai-alife-robot]
title = "ArXiv Search"
url = "https://x.gd/dOy4R"
entrySelector = "li.arxiv-result"
titleSelector = "p.title"
linkSelector = "a"
contentSelector = "span.abstract-short"
